name: "claat-cli"
description: "Runs claat Google Codelab CLI"
inputs:
  format:
    description: "export format"
    required: false
    default: "html"
  environment:
    description: "The destination environment of the export"
    required: false
    default: "web"
  auth:
    description: "The oAuth2 token"
    required: false
    default: ""
  source:
    description: "The source content to be converted into a static website"
    required: true
  output:
    description: "The output directory or `-` for stdout."
    required: true
    default: "."
outputs:
  output: # id of output
    description: 'The command output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: [ "/claat", "export", "-f", "${{ inputs.format }}", "-e", "${{ inputs.environment }}", "-auth", "${{ inputs.auth }}", "-o", "${{ inputs.output }}", "${{ inputs.source }}" ]
